### ISSUE TITLE
Error on applying deletions

### ISSUE THREAD

**Issue by WhiteyC** [MscrmTools/MsCrmTools.ScriptsFinder#14]
Selecting form scripts and set for deletion.
When applying changes, program crash in error NullReferenceException.
![xrmtoolkit_scriptfinder_error_20201201](https://user-images.githubusercontent.com/23065270/100686377-eba78700-33c9-11eb-83a0-3092678bc8b4.png)

---
- Deployment: Online
- DB Version: 9.1.0.25236
- Connection Controls Version: 1.2020.10.35
- XrmToolBox Version: 1.2020.11.42
- Tool Version: 1.2020.2.12

**Comment by MscrmTools** [comment]
Thank you for the feedback, I will check what could lead to this error

**Comment by MscrmTools** [comment]
Would it be possible to test with this version?
[MsCrmTools.ScriptsFinder.zip](https://github.com/MscrmTools/MsCrmTools.ScriptsFinder/files/5621320/MsCrmTools.ScriptsFinder.zip)

**Comment by WhiteyC** [comment]
Tested and worked perfectly for forms without error.
Can you use delete for Ribbon Command types?
Also noticed we can’t update ribbon scripts/rules.

Also I did come across a scenario that didn’t allow be to update forms.
The situation was a JS in the target was a managed solution and your “New Value” dropdown is likely filtered by customizable only and would not let me select a JS from the managed solution. So I was forced to do all the form changes manually one by one.
This drop-down shouldn’t be filtered by this and I was importing “All entities” not just from a solution.
Not a bug just an enhancement.

Awesome tool by the way. Saved me much pain.

[cid:image001.png@01D6C889.1109AD90]

Regards,

Craig White | Technical Solution Consulting & Development | +61 410 848 424 | craig.white@izee.com.au<mailto:craig.white@izee.com.au> | www.izee.com.au<http://www.izee.com.au/>

**Comment by MscrmTools** [comment]
Thank you for the feedback @WhiteyC

As for your comments:

- Ribbon are not exposed through API so I cannot add possibility to edit them. You can use Ribbon Workbench for that purpose

- Updating content of managed solution is not recommended by Microsoft. I guess this is why it is not exposed in the tool but I could definitively add this possibility

**Comment by WhiteyC** [comment]
*   Updating content of managed solution is not recommended by Microsoft. I guess this is why it is not exposed in the tool but I could definitively add this possibility
This is not updating a managed solution.
We are only using the JS scripts from the managed solution on forms used by the client. So adding dependencies to the managed solution, yes, but not modifying.
For example we have our managed solution in a client environment. They want the account quick create form to filter the lookups. We use the function from our managed solution rather than duplicating the code for simple client customizations. So as you can see we are not touching the original managed solution but need to select the web resource from that solution and add it to the form header etc.

Regards,

Craig White | Technical Solution Consulting & Development | +61 410 848 424 | craig.white@izee.com.au<mailto:craig.white@izee.com.au> | www.izee.com.au<http://www.izee.com.au/>

**Comment by MscrmTools** [comment]
Got it! I'm adding this capability right now

**Comment by WhiteyC** [comment]
Cheers 😊

Regards,

Craig White | Technical Solution Consulting & Development | +61 410 848 424 | craig.white@izee.com.au<mailto:craig.white@izee.com.au> | www.izee.com.au<http://www.izee.com.au/>
