### ISSUE TITLE
Object reference not set to an instance of an object when attempting to load scripts.

### ISSUE THREAD

**Issue by sudmanche** [MscrmTools/MsCrmTools.ScriptsFinder#15]
Error log attached, just trying to read scripts and events and get this error.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MsCrmTools.ScriptsFinder.ScriptsManager.LoadScripts(List`1 emds)
   at MsCrmTools.ScriptsFinder.ScriptsManager.Find(List`1 solutions, Version crmVersion)
   at MsCrmTools.ScriptsFinder.ScriptsFinder.<FindScripts>b__19_0(BackgroundWorker bw, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

XrmToolBox
    Assembly Version: 1.2021.6.51
    Win32 Version: 1.2021.6.51
    CodeBase: file:///C:/XrmToolbox/XrmToolBox.exe

XrmToolBox.Extensibility
    Assembly Version: 1.2021.6.51
    Win32 Version: 1.2021.6.51
    CodeBase: file:///C:/XrmToolbox/XrmToolBox.Extensibility.DLL

XrmToolBox.PluginsStore
    Assembly Version: 1.2021.6.51
    Win32 Version: 1.2021.6.51
    CodeBase: file:///C:/XrmToolbox/XrmToolBox.PluginsStore.DLL

McTools.Xrm.Connection
    Assembly Version: 1.2021.6.44
    Win32 Version: 1.2021.6.44
    CodeBase: file:///C:/XrmToolbox/McTools.Xrm.Connection.DLL

McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2021.6.44
    Win32 Version: 1.2021.6.44
    CodeBase: file:///C:/XrmToolbox/McTools.Xrm.Connection.WinForms.DLL

MsCrmTools.ScriptsFinder
    Assembly Version: 1.2020.2.12
    Win32 Version: 1.2020.2.12
    CodeBase: file:///C:/USERS/MUNS/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL

**Comment by sudmanche** [comment]
connection is via OAuth

**Comment by MscrmTools** [comment]
Yeah, I get this error time to time... I need to find out where this happens

**Comment by MscrmTools** [comment]
Well, I did not find an environment to reproduce the error...

**Comment by sudmanche** [comment]
So I have been creating smaller solutions to test this. I am getting 2 different issues.

1. If the Opportunity entity is in my solution, I get the error reported yesterday.
2. If The account entity is in my solution, I get the error below.

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MsCrmTools.ScriptsFinder.ScriptsManager.LoadViews(List`1 emds)
   at MsCrmTools.ScriptsFinder.ScriptsManager.Find(List`1 solutions, Version crmVersion)
   at MsCrmTools.ScriptsFinder.ScriptsFinder.<FindScripts>b__19_0(BackgroundWorker bw, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)


I will try and see what is special about scripts/events on these entities and get back to you.

**Comment by MscrmTools** [comment]
I tried by adding the same entities in a solution but did not get these errors...

**Comment by sudmanche** [comment]
On account there is shown a dependency to a system web resource, but that is not shown in the form libraries, and is not available to add. Perhaps this causes an issue?

![image](https://user-images.githubusercontent.com/3775226/124437391-4f869980-dd77-11eb-91d7-6afe6f6ac852.png)

**Comment by MscrmTools** [comment]
The tool is only parsing the FormXml content. So it must be something the tool expect but is not there.
Here is what is read
![image](https://user-images.githubusercontent.com/10774317/124439332-95dcf800-dd79-11eb-8b5a-542c8d115fdd.png)

What I can see is a "new" clienresources tag. Maybe that's the root cause. I will check in that direction

**Comment by MscrmTools** [comment]
Could you try with this version and tell me if the error still happens?

[MsCrmTools.ScriptsFinder.zip](https://github.com/MscrmTools/MsCrmTools.ScriptsFinder/files/6762845/MsCrmTools.ScriptsFinder.zip)

**Comment by sudmanche** [comment]
ok, so that partially fixed the problem, accounts was ok, and a different error on opportunity, but a meaningful error so I have been able to diagnose and resolve the problem.

The error was this:

```
System.Exception: Unable to find control with id : VENDOR_SUBGRID
   at MsCrmTools.ScriptsFinder.ScriptsManager.LoadScripts(List`1 emds)
   at MsCrmTools.ScriptsFinder.ScriptsManager.Find(List`1 solutions, Boolean loadManagedEntities, Version crmVersion)
   at MsCrmTools.ScriptsFinder.ScriptsFinder.<FindScripts>b__20_0(BackgroundWorker bw, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

```

the item was an editable grid which has been removed from the form, somehow the event on it had remained. So in the xml I removed the reference and now it is working.

```
                <event name="onsave" application="false" active="false" relationship="" control="VENDOR_SUBGRID">
                  <Handlers>
                    <Handler functionName="saveVendor" libraryName="nas_Opportunity_JavaScript_Library" handlerUniqueId="{81ac5a57-a4a5-38c8-82a1-db9556ac6a92}" enabled="true" parameters="" passExecutionContext="true" />
                  </Handlers>
                </event>

```

Thank you for the help.

**Comment by sudmanche** [comment]
Closing issue

**Comment by MscrmTools** [comment]
Thank you for helping resolving the issue!
So, yes, the code was expecting to find the control the event is linked to but it seems it can happen it's not always the case.

**Comment by sudmanche** [comment]
FYI, it seems the new form editor is prone to leaving orphaned events. We removed a field with a change event, and the event was left behind again.

**Comment by MscrmTools** [comment]
I will report this to Microsoft. Thanks
