### ISSUE TITLE
Escape `"` when generating CSV file

### ISSUE THREAD

**Issue by BetimBeja** [MscrmTools/MsCrmTools.ScriptsFinder#22]
When generating a CSV file the Parameters column can contain objects, and JSON properties contain the `"` double quote character. For the CSV reader to parse the file correctly those characters should be escaped by duplicating the character.

This is a possible solution:
![image](https://github.com/MscrmTools/MsCrmTools.ScriptsFinder/assets/11160171/34654029-fd6c-4462-8a06-4f169354eb01)

Source Code Reference:
https://github.com/MscrmTools/MsCrmTools.ScriptsFinder/blob/9a3d410b27bd0227e9710d060bf8427ee0574231/MsCrmTools.ScriptsFinder/ScriptsFinder.cs#L855

**Comment by MscrmTools** [comment]
Thank you! I will update the tool accordingly
