### ISSUE TITLE
Unhandled Exception with certain connections

### ISSUE THREAD

**Issue by TayloredMatt** [MscrmTools/MsCrmTools.ScriptsFinder#6]
Hi there,

I'm getting an Unhandled Exception when I try and find scripts for all entities - version 8.2 Dynamics 365 (Cloud). I manage a number of instances and I don't get the error with all of them and I can't think of anything that's different between them. 

I've attached the stack trace. Hoping you can help, this is a wonderful tool! :) 

Kind regards,

Matt

[ScriptFinderErrorDetails.txt](https://github.com/MscrmTools/MsCrmTools.ScriptsFinder/files/2383338/ScriptFinderErrorDetails.txt)

**Comment by MscrmTools** [comment]
Ok, thanks for reporting. Let me dig into code to search after NullException

**Comment by MscrmTools** [comment]
Can you test with this one?

[MsCrmTools.ScriptsFinder.zip](https://github.com/MscrmTools/MsCrmTools.ScriptsFinder/files/2383467/MsCrmTools.ScriptsFinder.zip)

**Comment by TayloredMatt** [comment]
> Can you test with this one?

It works perfectly, thank you so much!

**Comment by MscrmTools** [comment]
Ok, so you maybe will see some events with "N/A" information where I was expecting a value that is not there

**Comment by TayloredMatt** [comment]
Cheers for that, not sure how this works - do I have to close or do you? :)

**Comment by MscrmTools** [comment]
it will close automatically when I will commit code changes :)

**Comment by TayloredMatt** [comment]
Thank you for sorting so quickly, you've been a life-saver!

**Comment by MscrmTools** [comment]
You're welcome! Happy to help

**Comment by MscrmTools** [comment]
Broadly available in Plugins Store right now!
